### ISSUE TITLE
Universal aimbot and esp bug

### ISSUE THREAD

**Issue by TapsWuzHere** [Blissful4992/Miscellaneous#1]
Please can you fix universal aimbot and esp it crashes when i inject using synapse
its my favourite hack pleasee

**Comment by Blissful4992** [comment]
Hello,

Thanks for reaching out, the problem has been solved.

Sincerely,
Blissful

**Comment by TapsWuzHere** [comment]
Could i please get your discord?

**Comment by TapsWuzHere** [comment]
also the problem still exists roblox just freezes heres what i paste in the executor loadstring(game:HttpGet("https://raw.githubusercontent.com/Blissful4992/Miscellaneous/main/UNIVERSAL.lua"))()

**Comment by Blissful4992** [comment]
Ok should work now

**Comment by Raf1ic** [comment]
Is there an iOS executor for free?
